# include $(src)/Kbuild-mtk-custom-env

curr := platform/mtk_platform_common

mali_kbase-y += $(curr)/mtk_platform_common.o
mali_kbase-y += $(curr)/mtk_gpu_dvfs.o
mali_kbase-y += $(curr)/mtk_mfg_counter.o

ifeq ($(CONFIG_MTK_GPU_SWPM_SUPPORT),y)
mali_kbase-y += $(curr)/mtk_gpu_power_sspm_ipi.o
endif

ifeq ($(CONFIG_MALI_MTK_DEVFREQ),y)
mali_kbase-y += $(curr)/mtk_platform_devfreq.o
endif

ifeq ($(CONFIG_MALI_MTK_MEMTRACK),y)
mali_kbase-y += $(curr)/mtk_platform_memtrack.o
endif

ifeq ($(CONFIG_MALI_MTK_LOG_BUFFER),y)
mali_kbase-y += $(curr)/mtk_platform_logbuffer.o
endif

ifeq ($(CONFIG_MALI_MTK_ADAPTIVE_POWER_POLICY),y)
mali_kbase-y += $(curr)/mtk_platform_adaptive_power_policy.o
endif

ifeq ($(CONFIG_MALI_MTK_DEBUG_DUMP),y)
mali_kbase-y += $(curr)/mtk_platform_debug_dump_csg.o
mali_kbase-y += $(curr)/mtk_platform_debug_dump_cpu.o
mali_kbase-y += $(curr)/mtk_platform_debug_dump_kcpu.o
mali_kbase-y += $(curr)/mtk_platform_debug_dump_gpu.o
mali_kbase-y += $(curr)/mtk_platform_debug_dump_gpu_debugfs.o
mali_kbase-y += $(curr)/mtk_platform_debug_dump_infra_status.o
mali_kbase-y += $(curr)/mtk_platform_debug_dump_pm_status.o
mali_kbase-y += $(curr)/mtk_platform_debug_dump_enop_metadata.o
mali_kbase-y += $(curr)/mtk_platform_debug_dump_iter_cshw.o
mali_kbase-y += $(curr)/mtk_platform_debug_dump_queue_data.o
endif

ifeq ($(CONFIG_MALI_MTK_DIAGNOSIS_MODE),y)
mali_kbase-y += $(curr)/mtk_platform_diagnosis_mode.o
endif

ccflags-y += -I$(srctree)/drivers/devfreq/
ccflags-y += -I$(srctree)/drivers/gpu/mediatek/ged/include/
ccflags-y += -Wno-unused-variable -Wno-unused-function
